### PR TITLE
msvc intellisense update

### PR DESCRIPTION
**Pull request by hsdk123**

### CODE REVIEW

**Comment by mosra** [comment]
Okay, if they say in that blog post it has to be in cache, then I suppose this makes sense :)

**Comment by mosra** [comment]
Oh, about that comment, shouldn't that be `linux-gcc-x86` instead of `linux-gcc-x64`? Because Emscripten is 32-bit, with `sizeof(void*) == 4`, so pretending it's 64-bit may lead to nasty consequences.

Does it work well if you set it to `linux-gcc-x86` instead?

**Comment by hsdk123** [comment]
They actually both seem to work - honestly not sure what the difference is and I can't find any docs (...)

**Comment by mosra** [comment]
The difference is that one is 32-bit and the other is 64-bit. So I suppose you'd get different autocompletion hints, different predefined macros would be available (such as `CORRADE_TARGET_32BIT`), and so on. May not matter for most of the code, but in some lower-level parts it might.

Merged as 8202bb95c7d19143dde9339ca49e1b692ad316b7, thanks! If that's okay, I'll update the toolchains submodule in all repos next time I have something additional to push.

**Pull request closed without merging**
